# Generated by Django 5.0 on 2023-12-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Se o registro está ativo ou não', verbose_name='ativo')),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='data e hora de criação')),
                ('data_hora_ultima_alteracao', models.DateTimeField(auto_now=True, help_text='Data e hora da última alteração', verbose_name='data e hora da última alteração')),
                ('codigo', models.CharField(help_text='Nome padronizado do código', max_length=125, unique=True, verbose_name='código')),
                ('descricao', models.CharField(help_text='Descrição da utilidade dessa configuração', max_length=350, verbose_name='descrição')),
                ('valor', models.CharField(help_text='Valor da configuração', max_length=50, verbose_name='valor')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'db_table': 'configuracao',
                'ordering': ['-id'],
            },
        ),
    ]
